#!/bin/sh

### BEGIN INIT INFO
# Provides:		fake-whois
# Required-Start:	$local_fs $remote_fs $network $syslog $named
# Required-Stop:	$local_fs $remote_fs $network $syslog $named
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Start/stop the fake WHOIS server
### END INIT INFO

. /lib/lsb/init-functions

NAME="fake-whois"
CMD="/usr/local/bin/fake-whois.py"
PIDFILE="/var/run/${NAME}.pid"

start()
{
    log_action_begin_msg "Starting ${NAME}"
    start-stop-daemon --start --background --make-pidfile --pidfile ${PIDFILE} --startas ${CMD} > /dev/null
    log_action_end_msg $?
}

status()
{
    PID="$(cat ${PIDFILE} 2>/dev/null)" || true

    if [ ! -f ${PIDFILE} ] || [ -z "${PID}" ]
    then
        echo "${NAME} is not running"
        exit 3
    fi

    if ps "${PID}" > /dev/null 2>&1
    then
        echo "${NAME} is running"
        exit 0
    else
        echo "${NAME} is not running"
        exit 1
    fi
}

stop()
{
    log_action_begin_msg "Stopping ${NAME}"
    start-stop-daemon --stop -p ${PIDFILE} --oknodo > /dev/null
    log_action_end_msg $?
    [ -f ${PIDFILE} ] && rm -f ${PIDFILE}
}

usage()
{
    echo "Usage: service ${NAME} {start|stop|restart|status}"
}

case "$1" in
    start)
	start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
	status
        ;;
    *)
        usage
        exit 1
esac
exit 0
